### ISSUE TITLE
JsonMappingException

### ISSUE THREAD

**Issue by zimmerml** [axibase/atsd-api-java#1]
Hi,

executing
```java
GetSeriesQuery command = new GetSeriesQuery(entityName, metricName, tags, startTs.getTime(), endTs.getTime());
command.setAggregateMatcher(new SimpleAggregateMatcher(new Interval(1, IntervalUnit.SECOND), Interpolate.NONE, AggregateType.AVG));
List<GetSeriesResult> seriesList = dataService.retrieveSeries(command);
```

throws
```
com.axibase.tsd.client.AtsdServerException: Server Error (500), org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [simple type, class com.axibase.tsd.model.api.TimeSeriesInterpolationSettings] from JSON String; no single-String constructor/factory method (through reference chain: com.axibase.tsd.model.api.ApiTimeSeriesRequest["queries"]->com.axibase.tsd.model.api.ApiTimeSeriesQuery["aggregate"]->com.axibase.tsd.model.api.TimeSeriesAggregationSettings["interpolate"])
	at com.axibase.tsd.client.HttpClient.buildException(HttpClient.java:256)
	at com.axibase.tsd.client.HttpClient.requestObject(HttpClient.java:215)
	at com.axibase.tsd.client.HttpClient.requestData(HttpClient.java:193)
	at com.axibase.tsd.client.HttpClientManager.requestData(HttpClientManager.java:135)
	at com.axibase.tsd.client.DataService.retrieveSeries(DataService.java:61)
```

I don't know if this is a problem, but in my **aggregate** part of the json request:
   `{ [...] aggregate":{"types":["AVG"],"interval":{"count":1,"unit":"SECOND"},"interpolate":"NONE"}}]}`
**interval** is used instead of **period** like it is shown on [ATSD API](http://axibase.com/atsd/api/#aggregated-example).

Thank you in advance.

**Comment by rodionos** [comment]
We added support for additional interpolation options on the server side last week and the Java Java API is now out of sync. The **interpolate** field needs to be specified as an object whereas the mapping on the client assumes string type. We'll be updating the Java client early next week. Thank for you reporting the problem.

Both **period** and **interval** field names are currently supported for compatibility reasons. **interval** will be deprecated in a future release. 

Also, aggregation **type** field can be specified both as an array `"types": ["AVG"]` as well as singular value `"type": "AVG"`.


```json
            "aggregate" : {
               "types": ["AVG"],
               "period": {"count": 1, "unit": "HOUR"},
               "interpolate" : {
                  "type": "PREVIOUS"
               }
            }
```

```json
            "aggregate" : {
               "types": ["AVG"],
               "period": {"count": 1, "unit": "HOUR"},
               "interpolate" : {
                  "type": "LINEAR"
               }
            }
```

```json
            "aggregate" : {
               "types": ["AVG"],
               "period": {"count": 1, "unit": "HOUR"},
               "interpolate" : {
                  "type": "VALUE",
                  "value": 0
               }
            }
```

**Comment by rodionos** [comment]
Fixed. Please update your ATSD Java API client to the latest version.
